import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [Time, setTime] = useState(null);
  var $ = function (e) {
    return document.querySelector(e);
  };
  let count = 0;

  return (
    <div className={styles.container}>
      <Head>
        <title>Clicks Per Seconds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-[60px] flex justify-center">
        <input
          type="number"
          className="border-[1px] rounded-lg focus:outline-none w-[400px] h-[40px] pl-2.5"
          placeholder="Time (Seconds)"
          value={Time}
          onChange={function (e) {
            setTime(e.target.value);
          }}
        />
      </div>
      <div className="pt-[60px] flex justify-center">
        <button
          onClick={function () {
            count++;
            $("button").innerHTML = `Clicks: ${count}`;

            setInterval(function () {
              let cps = count / Time;

              $("span").innerHTML = `CPS: ${cps}`;
              $("button").disabled = true;
            }, Time * 1000);
          }}
          className="w-[400px] h-[300px] bg-slate-100 rounded-lg flex justify-center items-center text-3xl font-bold"
        >
          Clicks: 0
        </button>
      </div>
      <div className="pt-[20px] flex flex-col space-y-2">
        <h1 className="text-3xl font-bold text-center">Result</h1>
        <span className="text-center text-lg">CPS: </span>
      </div>
      <div className="flex justify-center">
        <div
          onClick={function () {
            window.location.reload();
          }}
          className="cursor-pointer fixed bottom-0 flex justify-center items-center justify-self-center w-[140px] h-[43px] mb-[10px] rounded-lg bg-red-500 text-3xl font-bold text-white"
        >
          Restart?
        </div>
      </div>
    </div>
  );
}
